--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.567.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/15/2022 4:20:50 AM
-- Source server version: 5.7.29
-- Source connection string: User Id=root;Host=127.0.0.1;Protocol=Ssh;Character Set=utf8;SSH Host=192.168.150.111;SSH Port=22;SSH User=root;SSH Authentication Type=Password
-- Target server version: 5.7.29
-- Target connection string: User Id=root;Host=127.0.0.1;Protocol=Ssh;Character Set=utf8;SSH Host=192.168.150.111;SSH Port=22;SSH User=root;SSH Authentication Type=Password
-- Run this script against dropit_shopping to synchronize it with drropit_sopping
--



SET NAMES 'utf8';
USE dropit_shopping;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Dropping constraints from Deliveries
--
ALTER TABLE Deliveries 
   DROP FOREIGN KEY FK_Deleveries_DeleverStatusID;
ALTER TABLE Deliveries 
   DROP FOREIGN KEY FK_Deleveries_ScheduleID;
ALTER TABLE Deliveries 
   DROP FOREIGN KEY FK_Deleveries_UserID;

--
-- Inserting data into table Deliveries
--
INSERT INTO Deliveries(DeliveryID, ScheduleID, UserID, DeliverStatusID, notes) VALUES
(1, 1, 1, 1, NULL);

--
-- Inserting data into table DeliveryStatus
--
INSERT INTO DeliveryStatus(StatusID, StatusName) VALUES
(1, 'Not completed'),
(2, 'Completed'),
(3, 'other');

--
-- Inserting data into table Schedule
--
INSERT INTO Schedule(TimeSlotID, TimeDate, FormatedAdress1, FormatedAdress2) VALUES
(1, '2022-06-06 00:00:00', '', NULL),
(2, '2022-06-21 00:00:00', NULL, NULL),
(3, '2022-06-22 00:00:00', NULL, NULL),
(4, '2022-06-19 00:00:00', NULL, NULL),
(5, '2022-06-23 00:00:00', NULL, NULL);

--
-- Inserting data into table Users
--
INSERT INTO Users(UserID, CompanyName, ConsulName_2, Adress, City, State, ZipCode, Phone_1, Phone_2, FormatedAdress) VALUES
(1, 'Telcom', 'Danni', 'Netiv 4', 'Natanya', 'Israel', NULL, '0505246951', NULL, NULL);
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

--
-- Creating constraints for Deliveries
--
ALTER TABLE Deliveries 
  ADD CONSTRAINT FK_Deleveries_DeleverStatusID FOREIGN KEY (DeliverStatusID)
    REFERENCES DeliveryStatus(StatusID) ON DELETE NO ACTION;
ALTER TABLE Deliveries 
  ADD CONSTRAINT FK_Deleveries_ScheduleID FOREIGN KEY (ScheduleID)
    REFERENCES Schedule(TimeSlotID) ON DELETE NO ACTION;
ALTER TABLE Deliveries 
  ADD CONSTRAINT FK_Deleveries_UserID FOREIGN KEY (UserID)
    REFERENCES Users(UserID) ON DELETE NO ACTION;